language: python
python:
  - "2.7"
before_install:
  - pip install codecov
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - pip install -r requirements.txt
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run --source='.' manage.py test
after_success:
  - codecov