# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-10-15 21:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clintime',
            field=models.TimeField(default=datetime.datetime(2018, 10, 15, 9, 0, tzinfo=utc), verbose_name=b'Time of Appointment'),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='clintime',
            field=models.TimeField(default=datetime.datetime(2018, 10, 15, 9, 0, tzinfo=utc), verbose_name=b'Time of Appointment'),
        ),
    ]
