# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-10-15 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientcontact',
            old_name='followupRequest',
            new_name='followup_request',
        ),
    ]
